mju-likelion/custard-pudding

- src/App.js
- src/components/Button/BigButton.js
- src/components/checkPage/SmallButton.js
- src/styles/GlobalStyle.js
작은 버튼, 큰 버튼 컴포넌트 제작
작은 버튼 - 버튼 크기는 미디어 쿼리로 설정, text props 지정, 호버 스타일 지정
큰 버튼 - 버튼 크기는 미디어 쿼리로 설정, 상태, text  props 지정
Close #4
> [Feature/#4] 버튼 컴포넌트 제작

- .eslintrc.json
- src/assets/imgs/big_cardLanyard.svg
- src/assets/imgs/big_card_lanyard.svg
- src/assets/imgs/card_string.svg
- src/assets/imgs/small_card_string.svg
- src/components/CardLanyard/CardLanyard.js
- src/components/checkPage/Input.js
- src/components/checkPage/SubTitle.js
- src/pages/Apply.js
- src/pages/Check.js
- src/pages/Main.js
학생증 끈 svg 첨부 및 학생증 카드 디자인 구현
서브 타이틀 구현
아이디 확인 input 구현
Close #7
> [Feature/#7] 지원 확인 학생증 구현

- src/components/CardLanyard/CardLanyard.js
- src/components/checkPage/Input.js
- src/components/checkPage/SubTitle.js
- src/pages/Apply.js
- src/pages/Main.js
Input 컴포넌트 caption, input, error message 통합
Close #9
> [Feature/#9] Input 컴포넌트 변경

- src/components/mainPage/ScrollBar.js
- src/components/mainPage/Wave.js
- src/messages/part.js
- src/pages/Main.js
현재 위치를 표시하는 animation 스크롤 바 구현
Closes #22
> [Feature/#22] 메인페이지 스크롤 바

- src/validation/idValidationSchema.js
학번과 관련한 정책에 대한 유효성 검사 구현
Closes #24
> [Feature/#24] 학번에 대한 유효성 검사 구현

- public/index.html
- src/components/PageLayout.js
- src/components/RoutesContainer.js
- src/components/mainPage/PartCard.js
- src/components/mainPage/ScrollBar.js
- src/components/mainPage/Wave.js
- src/styles/GlobalStyle.js
> [Feature/#29] UI 깨짐 수정

- package.json
- src/components/Footer.js
- src/components/mainPage/CopyMail.js
- src/components/mainPage/Toast.js
- yarn.lock
> [Feature/#18] Toast

- src/components/Button/BigButton.js
BigButton 컴포넌트의 반응형에 따른 사이즈 변화 추가 구현
Closes #42
> [Feature/#42] 반응형에 따른 버튼 컴포넌트 크기 변화 추가

- package.json
- src/Confetti.js
- src/pages/Complete.js
- yarn.lock
지원이 성공하였을 때 뜨는 Complete 페이지에 폭죽 효과를 추가
Close #47
> [Feature/#47] 지원 성공시 폭죽 효과 추가

- src/components/checkPage/CheckCard.js
- src/components/checkPage/resultData.js
- src/pages/Apply.js
- src/pages/Check.js
> [Feature/#51] 지원 확인 결과 실제 학번 값으로 변경

- src/components/Button/BigButton.js
- src/components/writePage/SubmitButton.js
- src/pages/ApplyWrite/index.js
- src/pages/Main.js
지원서 작성 페이지 제출하기 버튼 구현
Closes #56
> [Feature/#56] 지원서 작성 페이지 제출하기 버튼 구현

- src/styles/GlobalStyle.js
> [feature/#60] 가로 스크롤 방지

- src/api/ApplyWrite.js
- src/components/Footer.js
- src/components/writePage/ApplyAnswer.js
- src/components/writePage/HomeworkBox.js
- src/components/writePage/PersonalAgreeBox.js
- src/components/writePage/SubmitButton.js
- src/pages/ApplyWrite/data/HomeworkData.js
- src/pages/ApplyWrite/index.js
지원서 작성 페이지 api 예외처리 구현
Closes #63
> [Feature/#58] introduction page api exception

- src/components/mainPage/OpenChat.js
- src/components/mainPage/ScrollBar.js
- src/components/mainPage/Wave.js
-  헤더에 가려지는 문제 해결
-  사이즈 수정
Closes #81
> [Feature/#81] 스크롤 바 헤더에 가리는 문제 해결 및 사이즈 수정

- src/messages/part.js
> [Feature/#54] 메인페이지 내용 수정

- src/api/ApplyWrite.js
- src/components/writePage/HomeworkBox.js
- src/components/writePage/InfoInputBox.js
- src/components/writePage/PersonalAgreeBox.js
- src/components/writePage/SubmitButton.js
- src/components/writePage/UserInfoInput.js
- src/pages/ApplyWrite/data/HomeworkData.js
- src/pages/ApplyWrite/index.js
- src/validation/writeValidationSchema.js
작성 페이지 textarea error fix  
maxLength error fix 
지원자 정보 validation helpertext 추가 구현
Closes #76
> [Feature/#76] textarea focus & maxLength 해결

- src/components/Button/BigButton.js
- src/pages/Apply.js
> [Feature/#88] fix warning

- src/components/mainPage/ScrollBar.js
- src/styles/GlobalStyle.js
-  스크롤바의 영역 화면 전체 높이로 수정
- 기본 브라우저 스크롤바 숨김
Closes #93
> [Feature/#93] edit scrollbar

- src/api/ApplyWrite.js
- src/components/checkPage/SmallButton.js
- src/pages/Apply.js
- src/pages/ApplyWrite/index.js
- src/pages/Check.js
API를 요청하는 버튼이 한 번만 클릭 되도록 수정
: 서버 응답을 기다리는 loading 상태 추가
Closes #96
> [Feature/#96] click limit

- src/pages/Main.js
메인 페이지에 존재하는 편지svg를 s3로 업로드하여 사용
Close #97
> [Feature/#97] 메인 페이지의 이미지 렌더링 속도 개선

- src/components/writePage/HomeworkBox.js
- src/pages/ApplyWrite/index.js
- 파일 등록 후 삭제 한 뒤에 동일 파일 재 선택 시 변화가 감지되지 않는 문제 해결
- 파일 삭제 후 필수 필드가 모두 채워지지 않았음을 감지 하도록 수정
Closes #100
> [Feature/#100] 웹 파트 과제 파일 삭제 기능 추가 - #100

- src/pages/Apply.js
- src/pages/ApplyWrite/index.js
> [Feature]date validation

- package.json
- src/App.js
- src/hooks/useRouteTracker.js
- src/index.js
- yarn.lock
에러 수집을 위한 sentry 사용, GA 사용을 위한 설정
Closes #107
> [Feature/#107] sentry 및 GA 사용

- src/components/checkPage/Input.tsx
> [Refactor] Check and  Main
